### ISSUE TITLE
[Bug] Files still appear to be managed after projen eject

### ISSUE THREAD

**Issue by Chriscbr** [MarkMcCulloh/vscode-projen#26]
**Describe the bug**
If I run "projen eject" it seems like all of the files still appear to be managed by projen initially. I was able to fix it by reloading my window, but I wonder if there's a way to make this behavior automatic.

**To Reproduce**
Create a new projen project (npx projen new ...).
Open it in VS Code with the extension, and check that config files are tagged "PJ" in the file explorer.
Run `npx projen eject` from your command line.
Check VS Code file explorer and files still appear to be tagged with "PJ".

**Expected behavior**
I expected the file explorer to be updated with none of my files marked as projen managed.

**Screenshots**

**OS**
macOS

**Comment by MarkMcCulloh** [comment]
Thanks for reporting this! It appears this bug also prevents files from ever losing the "PJ" if they ever stopped being managed by projen by any means (eject or otherwise).

The fix for this is available now in [v0.0.30](https://github.com/MarkMcCulloh/vscode-projen/releases/tag/v0.0.30). If it's not resolved feel free to reopen this issue.
